package org.avd.kamin.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StatusEvidencijeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusEvidencijeAllPropertiesEquals(StatusEvidencije expected, StatusEvidencije actual) {
        assertStatusEvidencijeAutoGeneratedPropertiesEquals(expected, actual);
        assertStatusEvidencijeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusEvidencijeAllUpdatablePropertiesEquals(StatusEvidencije expected, StatusEvidencije actual) {
        assertStatusEvidencijeUpdatableFieldsEquals(expected, actual);
        assertStatusEvidencijeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusEvidencijeAutoGeneratedPropertiesEquals(StatusEvidencije expected, StatusEvidencije actual) {
        assertThat(expected)
            .as("Verify StatusEvidencije auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusEvidencijeUpdatableFieldsEquals(StatusEvidencije expected, StatusEvidencije actual) {
        assertThat(expected)
            .as("Verify StatusEvidencije relevant properties")
            .satisfies(
                e -> assertThat(e.getStatusEvidencijeNaziv()).as("check statusEvidencijeNaziv").isEqualTo(actual.getStatusEvidencijeNaziv())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusEvidencijeUpdatableRelationshipsEquals(StatusEvidencije expected, StatusEvidencije actual) {}
}
