package org.avd.kamin.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UlicaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUlicaAllPropertiesEquals(Ulica expected, Ulica actual) {
        assertUlicaAutoGeneratedPropertiesEquals(expected, actual);
        assertUlicaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUlicaAllUpdatablePropertiesEquals(Ulica expected, Ulica actual) {
        assertUlicaUpdatableFieldsEquals(expected, actual);
        assertUlicaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUlicaAutoGeneratedPropertiesEquals(Ulica expected, Ulica actual) {
        assertThat(expected)
            .as("Verify Ulica auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUlicaUpdatableFieldsEquals(Ulica expected, Ulica actual) {
        assertThat(expected)
            .as("Verify Ulica relevant properties")
            .satisfies(e -> assertThat(e.getUlicaNaziv()).as("check ulicaNaziv").isEqualTo(actual.getUlicaNaziv()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUlicaUpdatableRelationshipsEquals(Ulica expected, Ulica actual) {
        assertThat(expected)
            .as("Verify Ulica relationships")
            .satisfies(e -> assertThat(e.getGrad()).as("check grad").isEqualTo(actual.getGrad()))
            .satisfies(e -> assertThat(e.getNaselje()).as("check naselje").isEqualTo(actual.getNaselje()));
    }
}
