package org.avd.kamin.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VrstaUslugeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVrstaUslugeAllPropertiesEquals(VrstaUsluge expected, VrstaUsluge actual) {
        assertVrstaUslugeAutoGeneratedPropertiesEquals(expected, actual);
        assertVrstaUslugeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVrstaUslugeAllUpdatablePropertiesEquals(VrstaUsluge expected, VrstaUsluge actual) {
        assertVrstaUslugeUpdatableFieldsEquals(expected, actual);
        assertVrstaUslugeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVrstaUslugeAutoGeneratedPropertiesEquals(VrstaUsluge expected, VrstaUsluge actual) {
        assertThat(expected)
            .as("Verify VrstaUsluge auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVrstaUslugeUpdatableFieldsEquals(VrstaUsluge expected, VrstaUsluge actual) {
        assertThat(expected)
            .as("Verify VrstaUsluge relevant properties")
            .satisfies(e -> assertThat(e.getVrstaUslugeNaziv()).as("check vrstaUslugeNaziv").isEqualTo(actual.getVrstaUslugeNaziv()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVrstaUslugeUpdatableRelationshipsEquals(VrstaUsluge expected, VrstaUsluge actual) {}
}
